language: ruby
sudo: false
rvm:
  - 2.2.3
branches:
  only:
    - master
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer