# Site-specific settings
name: Anotherbyte # site title
url: http://www.anotherbyte.net/ # the base hostname & protocol for your site
description: >
  Mark's blog. Notes on Australian news, society, politics, and events.
  Commentary on software development, games, the intersection of copyright and technology, and science.
author: Mark

# pagination
paginate: 5 # number of posts per page
paginate_path: "/page:num/" # destination of the pagination pages
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
baseurl: '' # the subpath of your site, e.g. /blog/
host: 0.0.0.0 # for local server
feed:
  path: feed.xml