# General Jekyll Config
highlighter: pygments
safe: false
url: http://anotherbyte.net
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor, 'tag/']
paginate: 5
gems:
  - jekyll-sitemap